### ISSUE TITLE
get_by_argument for duplicate values

### ISSUE THREAD

**Issue by tianbaoluo** [shuoli84/sweep-bptree#24]
I want to quick find n-th element in a vector, such as in vector [0.1, 0.2, 0.2, 0.2], the 2nd element is 0.2, but BPlusTreeMap would remove duplicate values.
Can BPlusTreeMap keep track the count of the same value in InnerNode?

example:
```
  use sweep_bptree::BPlusTreeMap;
  use sweep_bptree::argument::count::Count;

// use Count as Argument to create a order statistic tree
  let mut map = BPlusTreeMap::<i32, (), Count>::new();
  map.insert(1, ());
  map.insert(1, ());
  map.insert(1, ());
  for idx in 0..5 {
    println!("{}:\t{:?}", idx, map.get_by_argument(idx));
  }
```
It only print the 1th element:
```
0:      Some((1, ()))
1:      None
2:      None
3:      None
4:      None
```

**Comment by YeungOnion** [comment]
It may make more sense to instead wrap your type such that `cmp` never returns `Ordering::Equal` perhaps

```rs
use sweep_bptree::{tree::count::Count, BPlusTreeMap};

#[derive(Clone, Debug)]
pub struct NonEqWrapper<T> {
    inner: T,
}

impl<T> NonEqWrapper<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T> PartialEq for NonEqWrapper<T> {
    fn eq(&self, _: &Self) -> bool {
        false
    }
}

impl<T> Eq for NonEqWrapper<T> {}

impl<T: Ord> PartialOrd for NonEqWrapper<T> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        use std::cmp::Ordering;
        Some(match self.inner.cmp(&other.inner) {
            Ordering::Greater => Ordering::Greater,
            Ordering::Less | Ordering::Equal => Ordering::Less,
        })
    }
}

impl<T: Ord> Ord for NonEqWrapper<T> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.partial_cmp(other).unwrap()
    }
}

pub fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut map = BPlusTreeMap::<NonEqWrapper<i32>, (), Count>::new();
    map.insert(NonEqWrapper::new(1), ());
    assert_ne!(NonEqWrapper::new(1), NonEqWrapper::new(1));
    map.insert(NonEqWrapper::new(1), ());
    map.insert(NonEqWrapper::new(1), ());
    map.insert(NonEqWrapper::new(1), ());
    for idx in 0..5 {
        println!("{}:\t{:?}", idx, map.get_by_augmentation(idx));
    }
    Ok(())
}
```

but a different approach is to associate the Key to a value describing the count of observations and rewrite Count to sum values. Note that this is exactly what I'll be doing for a project and I plan to contribute it as an example to get insight from the author before I use this in my project.

**Comment by YeungOnion** [comment]
> but a different approach is to associate the Key to a value describing the count of observations and rewrite Count to sum values.

@shuoli84 I had intended to do the above but I just noticed that the augmentation doesn't seem to be intended for use when values change. 

Can you help me understand the motivation here? Perhaps if I understand then I may be able to think about my problem differently.

**Comment by shuoli84** [comment]
Right, currently values are not considered when building the augmentation. The reason behind this is "not all changes for value are tracked by the tree", the value could be something like "wrapped in Arc mutex".

**Comment by YeungOnion** [comment]
Thanks, this makes sense to me since it's a collection and other tree implementations don't rely on values to uphold invariants.

I'm wondering if there's a way to implement some `struct CountIncludingDuplicates(usize)` that could replace `Count` in @tianbaoluo's code and it exhibit the behavior they expected.

Does `BPlusTree::insert` guarantee that `Augmentation::visit_` are called? Or are they only called when keys are inserted?

**Comment by shuoli84** [comment]
You mean Augmentation::from_(inner, leaf)? Currently, they only get called if key changed. My first thought(not sure if it works): Create a new type for key, which also contains a usize, e.g. existing count etc.

**Comment by shuoli84** [comment]
How would you delete an item from tree? If only get a number, then deletion's logic is little bit tricky. 
```
if count > 1 {
  // decrease the count by update
} else {
  // delete the key as its occurence is 0
}
```

**Comment by YeungOnion** [comment]
> You mean Augmentation::from_(inner, leaf)? Currently, they only get called if key changed. My first thought(not sure if it works): Create a new type for key, which also contains a usize, e.g. existing count etc. 

Yes, `from_(inner, leaf)`. Hmm, this requires updating a key, but would this be as expensive as key removal and reinsertion? I use the term "_re_ -insertion" as the keys should be `eq` so they can be found and ordered by value instead of their multiplicity.

And you also mention that deletion would be tricky as one would actually have to use key update and possible deletion. Fortunately for me, my use case, I'm less interested in performing this kind of reduction of multiplicity with possible key deletion.

Do you think your API could support a non-idempotent key insertion that updates Augmentation as the tree is traversed to find a key? This would allow the example is the issue to replace usage of `insert` with this other insert (perhaps called `force_insert`?).

---

I recognize that this is a fundamentally different operation than before so I understand keeping this out of scope. For specificity, 

```rs
assert_eq!(bp_tree, BPlusTree::bulk_load(<bp_tree as Into::<std::collections::BTreeSet>>.into().into_iter()));
```

Would hold for all BPlusTree's as Augmentations are functions of subtree's keys and Augmentations.

While still path-independent, this new kind of insert would not obey this invariant as it's a function of both kinds of insert operations.

**Comment by shuoli84** [comment]
I don't quite understand `force_insert`, is it a version of update which calls `Augmentation::from_*` for updated values (not inserted)?

**Comment by YeungOnion** [comment]
Nearly, it would behave the same as `insert` but instead guarantees `Augmentation::from_*` is called. The typical tree insertion is idempotent. I realize that the example from this issue is not actually the behavior.


Example (WIP, started on mobile)
---
An empty tree set B=2, storing some integer augmentation with Count. Parenthesis denote Augmentation values. Brackets denote keys in inner node (only one key or inner for B=1)
```text
        (0)
    (0) [] (0)
```

calls `force_insert(2)` or `insert(2)`
```text
      (1)
    (0) [2] (0)
```
adds a key `2`, therefore updates Augmentations along the path to that key.

calls `force_insert(2)`
```text
      (2)
    (0) [2] (0)
```
does not add key `2` as it's already there, as `force_insert` ensures update of Augmentations along the path to that key.

calls `insert(2)`
```text
      (2)
    (0) [2] (0)
```
Key `2` already in tree, so no augmentation updates.

calls `force_insert(1)` or `insert(1)`
```text
      (2)
   (1) [2] (0)
    /         \ 
(0) [1] (0)   (0) [] (0)
```

calls `insert(1)`
```text
      (2)
   (1) [2] (0)
    /         \ 
(0) [1] (0)   (0) [] (0)
```

calls `force_insert(1)`
```text
      (2)
   (2) [2] (0)
    /         \ 
(0) [1] (0)   (0) [] (0)
```

**Comment by shuoli84** [comment]
Thanks for this Good explaination. I see why it called "force". 

I think this approach is tricky, as you mentioned, the key or value itself lost the info of "count", only use augmentation to track it, but augmentation is something only depends on key, this introduced inconsistancy.

It seems reasonable to let augmentation depends on value and get called if "value" updated under some constraints. E.g: value is copy + clone, or user knows exactly what they do (E.g, for values like Arc<Mutex<>>, it is obvious that augmentations depends on value won't get updated).

I still think """(Key, usize)""" is the way to go, let me implement this to sort it out. :)
